server:
  name: user-edge-service
  port: 8082

thrift:
  user:
    ip: user-service
    port: 7911
  message:
    ip: message-service
    port: 9090

spring:
  redis:
    host: ${redis.address}
    port: 6379
    timeout: 30000